#!/usr/bin/env bash
# Script to display subdomain and destination

display_domain() {

	if [ -z "$2" ]
	then
		dig "www.$1" | awk -v subdo="www" '/;; ANSWER SECTION:/ {getline; print "The subdomain " subdo " is a " $4 " record and points to " $5}'
		dig "lb-01.$1" | awk -v subdo="lb-01" '/;; ANSWER SECTION:/ {getline; print "The subdomain " subdo " is a " $4 " record and points to " $5}'
		dig "web-01.$1" | awk -v subdo="web-01" '/;; ANSWER SECTION:/ {getline; print "The subdomain " subdo " is a " $4 " record and points to " $5}'
		dig "web-02.$1" | awk -v subdo="web-02" '/;; ANSWER SECTION:/ {getline; print "The subdomain " subdo " is a " $4 " record and points to " $5}'
	else
		dig "$2.$1" | awk -v subdo="$2" '/;; ANSWER SECTION:/ {getline; print "The subdomain " subdo " is a " $4 " record and points to " $5}'
	fi
	return 0
}

display_domain "$1" "$2"
