#!/usr/bin/env bash
# Script to display subdomain and destination
#record = `dig "$2.$1" | awk '/^$1\.$2\.tech/ {print}' | awk '/[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+/ {print}'`
#record = $(`dig "$2.$1" | awk '/^$1\.$2\.tech/ {print $4}') 
#destination = $(`dig "$2.$1" | awk '/^$1\.$2\.tech/ {print $5}')
#record = awk '/^lb-01\.hilbertonians\.tech/ {print}' | awk '/[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+/ {print}'

#$sub = $1

#dig "$2.$1" | awk "/^$1\.$2\.tech/ {print  $4 $5}"
#echo "The subdomain $2 is a $record record and points to [DESTINATION]"

display_domain() {

	if [ -z $2 ]
	then
		dig "www.$1" | awk -v dom="$1" '/^$1\.$2\.tech/ {print "The subdomain is a " $4 " record and points to " $5}'
		dig "lb-01.$1" | awk "/^$1\.$2\.tech/ {print "The subdomain is a " $4 " record and points to " $5}"
		dig "web-01.$1" | awk "/^$1\.$2\.tech/ {print "The subdomain is a " $4 " record and points to " $5}"
		dig "web-02.$1" | awk "/^$1\.$2\.tech/ {print "The subdomain is a " $4 " record and points to " $5}"
		
	else
		dig "$2.$1" | awk -v dom="$1" -v subdo="$2" '/^subdo\.dom/ {print "The subdomain " subdo "is a " $4 " record and points to " $5}'
	fi
	return 0
}

display_domain $1 $2
