#!/usr/bin/env bash
#curl -T
if [ $# -eq 4 ]
then
	scp -i "$4" "$1" "$3""@""$2":~/
	#echo "Path $1 ip $2 username $3 key $4"
else
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
