#!/usr/bin/env bash
#Infinite loop

trap 'echo "I hate the kill command"; exit' SIGTERM
trap 'echo "Y U no love me?!"; exit' SIGINT
trap 'rm /var/run/holbertonscript.pid; exit' SIGQUIT SIGTERM

echo $$ > "/var/run/holbertonscript.pid"
while ((1))
do
	echo "To infinity and beyond"
done
